### ISSUE TITLE
When using the options you need to either supply them all or none

### ISSUE THREAD

**Issue by dan-gamble** [KolceThompsonCo/postcss-lh#10]
Originally i was using:

```
require('postcss-lh'),
```

And the worked fine then i wanted to change my `rhythmUnit` so i did:

```
  require('postcss-lh')({
    rhythmUnit: 'vr'
  }),
```

But this ended up making `getLineHeight` return `undefined` and i think it's because of this line: `decl.parent.selector === opts.rootSelector &&`

When you use one of the keys in the `opts` the object gets replaced with an object the just has them keys so it can't find `opts.rootSelector` because the key doesn't exist.

I'd suggest merging the `defaults` object with the `opts` object if the keys exist.

I'll see if i can have a go at this today myself :)

**Comment by jameskolce** [comment]
That's interesting, thank you for reporting this issue and I'll merge your pull request in a second! 
Thanks again!

**Comment by jameskolce** [comment]
Done, I'll release a patch version soon!

**Comment by dan-gamble** [comment]
Awesome, i just edited my local and production node_modules for the time being 👍

**Comment by jameskolce** [comment]
Cool! The new version should is already available though 👍

**Comment by dan-gamble** [comment]
I can only see 1.1.1 on npm

**Comment by jameskolce** [comment]
Oh sorry, I released it on Github but totally forgot about NPM, but try again now, I just published 1.1.2!

**Comment by dan-gamble** [comment]
Haha no worries, thanks! Will update my projects now :)

**Comment by jameskolce** [comment]
Great, no problem!
