### ISSUE TITLE
default params fail in node < 6

### ISSUE THREAD

**Issue by BarryThePenguin** [KolceThompsonCo/postcss-lh#13]
Default function params `(opts = defaults)` are only available in node > 6 http://node.green/#default-function-parameters

Is it possible to remove these for now so it works on other node versions. I'm happy to submit a PR :grinning:

**Comment by jameskolce** [comment]
Yeah, I don't have any problem with changing it and if you can submit a PR it would be really really helpful! I can release a new patch version after that.
Thanks!

**Comment by jameskolce** [comment]
Okay, v1.1.3 is now on NPM!

**Comment by BarryThePenguin** [comment]
Fantastic, thanks!
