### ISSUE TITLE
Vertical rhythm grid

### ISSUE THREAD

**Issue by iamfrntdv** [KolceThompsonCo/postcss-lh#15]
Could you please help is there any tool or plugin that creates vertical rhythm grid for development that you could advise?

**Comment by jameskolce** [comment]
Sure! I haven't used visual grids lately (I just trust by making all the spaces with this lh unit) but I have used http://basehold.it/ before, which basically adds lines as background for the body. I think it's also possible to use a gradient background with CSS, you can research for "css gradient for vertical rhythm" on Google and you could find some variations.
I'm also the lead developer of https://github.com/ConciseCSS/concise.css and I do plan to create a tool for this when I get more free time, but I don't have a specific timeline yet :D

**Comment by jameskolce** [comment]
Let me know if that works for you! Also, I was thinking that maybe it would be possible to create something with PostCSS to automatize the grid creation by getting the line-height directly from the code, but I still need more time, I haven't even fixed your previous issue yet (but soon, sorry about that).
