### ISSUE TITLE
getlineheight - bug in linux

### ISSUE THREAD

**Issue by JimiShah** [KolceThompsonCo/postcss-lh#7]
In index.js line 2
`const getLineHeight = require('./lib/getLineHeight');`
getLineHeight has L & H capital, but the file name is getlineheight.js, This works fine in Mac but breaks in linux. Please rename the file to getLineHeight.js

**Comment by jameskolce** [comment]
Fixed with https://github.com/KolceThompsonCo/postcss-lh/commit/35dea0e71f435de29f4c9e1f913302147896fa2a Thank you!

**Comment by jameskolce** [comment]
The new version is now available via NPM!
